"""add is_blocked columns to attendance and documents

Revision ID: afe78f2fa26e
Revises: 20260118_email_phone
Create Date: 2026-01-19 12:47:23
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'afe78f2fa26e'
down_revision: Union[str, None] = '20260118_email_phone'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Add is_blocked columns with server_default for SQLite compatibility
    op.add_column('attendance', sa.Column('is_blocked', sa.Boolean(), server_default='0', nullable=False, comment='Чи заблоковано редагування запису (місяць погоджено)'))
    op.add_column('attendance', sa.Column('blocked_reason', sa.String(length=500), nullable=True, comment='Причина блокування запису'))

    op.drop_index(op.f('ix_attendance_is_correction'), table_name='attendance')
    op.create_index(op.f('ix_attendance_is_blocked'), 'attendance', ['is_blocked'], unique=False)

    # Add columns for documents
    op.add_column('documents', sa.Column('is_blocked', sa.Boolean(), server_default='0', nullable=False, comment='Чи заблоковано редагування документа (завантажено скан або оброблено)'))
    op.add_column('documents', sa.Column('blocked_reason', sa.String(length=500), nullable=True, comment='Причина блокування документа'))

    # Set is_blocked for existing documents where scan exists or status is processed
    op.execute("UPDATE documents SET is_blocked = 1 WHERE file_scan_path IS NOT NULL OR status = 'processed'")

    op.create_index(op.f('ix_documents_is_blocked'), 'documents', ['is_blocked'], unique=False)
    op.alter_column('documents', 'doc_type',
               existing_type=sa.VARCHAR(length=15),
               type_=sa.Enum('VACATION_PAID', 'VACATION_UNPAID', 'TERM_EXTENSION', 'VACATION_MAIN', 'VACATION_ADDITIONAL', 'VACATION_CHORNOBYL', 'VACATION_CREATIVE', 'VACATION_STUDY', 'VACATION_CHILDREN', 'VACATION_MATERNITY', 'VACATION_CHILDCARE', 'VACATION_UNPAID_STUDY', 'VACATION_UNPAID_MANDATORY', 'VACATION_UNPAID_AGREEMENT', 'VACATION_UNPAID_OTHER', 'TERM_EXTENSION_CONTRACT', 'TERM_EXTENSION_COMPETITION', 'TERM_EXTENSION_PDF', name='documenttype'),
               existing_nullable=False)
    op.alter_column('staff', 'department',
               existing_type=sa.VARCHAR(length=100),
               nullable=False,
               existing_server_default=sa.text("'Кафедра комп''ютерних та інформаційних технологій'"))
    op.alter_column('staff', 'work_schedule',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.Enum('STANDARD', 'PART_TIME', name='workscheduletype'),
               nullable=False,
               existing_server_default=sa.text("'STANDARD'"))
    op.drop_index(op.f('ix_tabel_approval_correction_sequence'), table_name='tabel_approval')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_tabel_approval_correction_sequence'), 'tabel_approval', ['correction_sequence'], unique=False)
    op.alter_column('staff', 'work_schedule',
               existing_type=sa.Enum('STANDARD', 'PART_TIME', name='workscheduletype'),
               type_=sa.VARCHAR(length=20),
               nullable=True,
               existing_server_default=sa.text("'STANDARD'"))
    op.alter_column('staff', 'department',
               existing_type=sa.VARCHAR(length=100),
               nullable=True,
               existing_server_default=sa.text("'Кафедра комп''ютерних та інформаційних технологій'"))
    op.drop_index(op.f('ix_documents_is_blocked'), table_name='documents')
    op.alter_column('documents', 'doc_type',
               existing_type=sa.Enum('VACATION_PAID', 'VACATION_UNPAID', 'TERM_EXTENSION', 'VACATION_MAIN', 'VACATION_ADDITIONAL', 'VACATION_CHORNOBYL', 'VACATION_CREATIVE', 'VACATION_STUDY', 'VACATION_CHILDREN', 'VACATION_MATERNITY', 'VACATION_CHILDCARE', 'VACATION_UNPAID_STUDY', 'VACATION_UNPAID_MANDATORY', 'VACATION_UNPAID_AGREEMENT', 'VACATION_UNPAID_OTHER', 'TERM_EXTENSION_CONTRACT', 'TERM_EXTENSION_COMPETITION', 'TERM_EXTENSION_PDF', name='documenttype'),
               type_=sa.VARCHAR(length=15),
               existing_nullable=False)
    op.drop_column('documents', 'blocked_reason')
    op.drop_column('documents', 'is_blocked')
    op.drop_index(op.f('ix_attendance_is_blocked'), table_name='attendance')
    op.create_index(op.f('ix_attendance_is_correction'), 'attendance', ['is_correction'], unique=False)
    op.drop_column('attendance', 'blocked_reason')
    op.drop_column('attendance', 'is_blocked')
    # ### end Alembic commands ###
