"""add stale_lock_count to documents

Revision ID: d2bf0d856ef5
Revises: c8f2e9a5d6b1
Create Date: 2026-01-22 09:42:12
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd2bf0d856ef5'
down_revision: Union[str, None] = 'c8f2e9a5d6b1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('stale_lock_count', sa.Integer(), nullable=False, server_default='0', comment='Кількість циклів застарілості (скільки разів документ ставав stale)'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_tabel_approval_correction_sequence'), 'tabel_approval', ['correction_sequence'], unique=False)
    op.alter_column('staff', 'work_schedule',
               existing_type=sa.Enum('STANDARD', 'PART_TIME', name='workscheduletype'),
               type_=sa.VARCHAR(length=20),
               nullable=True,
               existing_server_default=sa.text("'STANDARD'"))
    op.alter_column('staff', 'department',
               existing_type=sa.VARCHAR(length=100),
               nullable=True,
               existing_server_default=sa.text("'Кафедра комп''ютерних та інформаційних технологій'"))
    op.drop_index(op.f('ix_documents_status_changed_at'), table_name='documents')
    op.alter_column('documents', 'status',
               existing_type=sa.Enum('DRAFT', 'SIGNED_BY_APPLICANT', 'APPROVED_BY_DISPATCHER', 'SIGNED_DEP_HEAD', 'AGREED', 'SIGNED_RECTOR', 'SCANNED', 'PROCESSED', 'ON_SIGNATURE', 'SIGNED', name='documentstatus'),
               type_=sa.VARCHAR(length=12),
               existing_nullable=False)
    op.alter_column('documents', 'doc_type',
               existing_type=sa.Enum('VACATION_PAID', 'VACATION_UNPAID', 'TERM_EXTENSION', 'VACATION_MAIN', 'VACATION_ADDITIONAL', 'VACATION_CHORNOBYL', 'VACATION_CREATIVE', 'VACATION_STUDY', 'VACATION_CHILDREN', 'VACATION_MATERNITY', 'VACATION_CHILDCARE', 'VACATION_UNPAID_STUDY', 'VACATION_UNPAID_MANDATORY', 'VACATION_UNPAID_AGREEMENT', 'VACATION_UNPAID_OTHER', 'TERM_EXTENSION_CONTRACT', 'TERM_EXTENSION_COMPETITION', 'TERM_EXTENSION_PDF', 'EMPLOYMENT_CONTRACT', 'EMPLOYMENT_COMPETITION', 'EMPLOYMENT_PDF', name='documenttype'),
               type_=sa.VARCHAR(length=15),
               existing_nullable=False)
    op.drop_column('documents', 'stale_lock_count')
    op.drop_index(op.f('ix_attendance_is_blocked'), table_name='attendance')
    op.create_index(op.f('ix_attendance_is_correction'), 'attendance', ['is_correction'], unique=False)
    op.alter_column('attendance', 'is_blocked',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    # ### end Alembic commands ###
